name: Production Build

on:
  workflow_call:

env:
  DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
  DATABASE_DIRECT_URL: ${{ secrets.CI_DATABASE_URL }}

jobs:
  build:
    name: Build API v2
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:13
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: calendso
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
      - name: Cache API v2 production build
        uses: actions/cache@v2
        id: cache-api-v2-build
        with:
          path: |
            **/dist/**
          key: ${{ runner.os }}-api-v2-build-${{ hashFiles('yarn.lock') }}-${{ hashFiles('apps/api/v2/**.[jt]s', 'apps/api/v2/**.[jt]sx', '!**/node_modules') }}-${{ github.event.pull_request.number || github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-api-v2-build-${{ hashFiles('yarn.lock') }}-${{ hashFiles('apps/api/v2/**.[jt]s', 'apps/api/v2/**.[jt]sx', '!**/node_modules') }}-${{ github.event.pull_request.number || github.ref }}-

      - name: Log Cache Hit
        if: steps.cache-api-v2-build.outputs.cache-hit == 'true'
        run: echo "Cache hit for API v2 build. Skipping build."
      - name: Run build
        if: steps.cache-api-v2-build.outputs.cache-hit != 'true'
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn workspace @calcom/api-v2 run generate-schemas
          rm -rf apps/api/v2/node_modules
          yarn install
          yarn workspace @calcom/api-v2 run build
        shell: bash
